#version 310 es
// all about types and layouts
// https://www.opengl.org/wiki/Layout_Qualifier_%28GLSL%29

layout(local_size_x = 32) in;
layout(std430) buffer;

// indicates how many alements are present in vectors
uniform uint elements;

layout(binding = 0) writeonly buffer Output {
    int elements[];
} output_data;

layout(binding = 1) readonly buffer Input0 {
    int elements[];
} input_data0;

layout(binding = 2) readonly buffer Input1 {
    int elements[];
} input_data1;

void main()
{
    uint index = gl_GlobalInvocationID.x;

    if(index >= elements)
        return;

    output_data.elements[index] = input_data0.elements[index] + input_data1.elements[index];
}
